---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: geerlingguy.nfs
      when: install_nfs is defined and (install_nfs == True or install_nfs == "true" or install_nfs == "yes")

  tasks:
    - name: Install requested packages
      package:
        name: "{{ install_packages.split(',') }}"
      when: install_packages is defined and install_packages != ""

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      when: update_os is defined and (update_os == True or update_os == "true" or update_os == "yes")
